[package]
name = "bc_indicators"
version = "0.1.0"
edition = "2024"

[dependencies]
bc_utils = {path = "../bc_utils"}
bc_utils_lg = {path = "../bc_utils_lg"}

num-traits = "^0.2.19"
rustc-hash = "1.1"
