[package]
name = "bc_settings"
version = "0.1.1"
edition = "2024"

[lib]
name = "bc_settings"
path = "src/lib.rs"

[dependencies]
bc_utils_lg ={ path = "../bc_utils_lg" }

serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
